apiVersion: batch/v1
kind: CronJob
metadata:
  name: pcc-daily-pipeline
  namespace: pcc-system
  labels:
    app: pcc-pipeline
    type: cronjob
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pcc-pipeline
            type: daily-run
        spec:
          serviceAccountName: pcc-service-account
          restartPolicy: OnFailure
          containers:
          - name: pcc-daily-pipeline
            image: pcc-pipeline:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DRY_RUN
              value: "false"
            - name: PYTHONPATH
              value: "/app/src"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/config/gcp-service-account.json"
            - name: TZ
              value: "UTC"
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
            volumeMounts:
            - name: config-volume
              mountPath: /app/src/config/config.yaml
              subPath: config.yaml
            - name: secrets-volume
              mountPath: /app/config/gcp-service-account.json
              subPath: gcp-service-account.json
              readOnly: true
            - name: logs-volume
              mountPath: /app/logs
            - name: models-volume
              mountPath: /app/src/models
            command:
            - python
            - scripts/daily_pipeline_run.py
            - --mode
            - prod
            - --force-latest
          volumes:
          - name: config-volume
            configMap:
              name: pcc-config
          - name: secrets-volume
            secret:
              secretName: pcc-secrets
          - name: logs-volume
            emptyDir: {}
          - name: models-volume
            emptyDir: {}
          backoffLimit: 3
          activeDeadlineSeconds: 3600  # 1 hour timeout
