# config.yaml — pipeline configuration for PCC

bq:
  # Input snapshot (daily partitioned)
  source_table: your-project.your-dataset.source_table

  # Output table destination (MVP-ready)
  output_table: ales-sandbox-465911.PCC_EPs.pcc_inference_output
  
  # Monitoring table for logging pipeline runs
  monitoring_table: ales-sandbox-465911.PCC_EPs.pcc_monitoring_logs
  
models:
  # Local paths to model artifacts (can later be migrated to GCS)
  classifier_path: src/models/pcc_v0.1.1.pkl

  # Embedding model used to generate vectors in snapshot
  embedding_model: all-MiniLM-L6-v2

runtime:
  # Runtime mode: dev | prod | dry_run (used for CLI behavior and Flyte switching)
  mode: dev

  # Prevent writing to BigQuery if true (used during development/testing)
  dry_run: false

  # Date partition to process — format: YYYYMMDD (used for snapshot resolution)
  partition_date: 20250101
