name: Daily Inference Pipeline

on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 UTC = 9:00 ART
  workflow_dispatch:

jobs:
  run-inference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Set up GCP credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | sed 's/\\n/\n/g' > ${{ github.workspace }}/gcp-key.json

      - name: Show GCP key file (first 20 lines)
        run: |
          cat -n ${{ github.workspace }}/gcp-key.json | head -20

      - name: Show GCP key file as base64
        run: |
          echo "==== GCP KEY FILE BASE64 ===="
          base64 ${{ github.workspace }}/gcp-key.json
          echo "==== END OF FILE ===="

      - name: Run inference pipeline
        id: run_pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          set -o pipefail
          python scripts/run_pipeline.py 2>&1 | tee pipeline_output.log

      - name: Send failure notification email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[ALERT] PCC Daily Inference Pipeline Failed"
          to: alejandroa.garay.ag@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            The PCC daily inference pipeline failed.

            Date: ${{ github.event.head_commit.timestamp }}
            Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Error log (last 50 lines):
            
            ${{ steps.run_pipeline.outputs.log_tail }}
        env:
          LOG_FILE: pipeline_output.log

      - name: Get last 50 lines of log for email
        if: failure()
        id: get_log_tail
        run: |
          tail -n 50 pipeline_output.log > log_tail.txt
          echo "log_tail<<EOF" >> $GITHUB_OUTPUT
          cat log_tail.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT 